function S = g_S(in1,in2)
%G_S
%    S = G_S(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Dec-2019 15:42:32

r1 = in1(1,:);
r2 = in1(2,:);
ro1 = in2(1,:);
ro2 = in2(2,:);
ro3 = in2(3,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = t2+t3;
t5 = sqrt(t4);
t6 = 1.0./t4.^(3.0./2.0);
t7 = ro1+ro2+ro3;
S = reshape([t6.*(ro1.*t3.*2.0+ro2.*t3.*2.0+ro3.*t3.*2.0-t2.*t5.*6.0-t3.*t5.*6.0),r1.*r2.*t6.*t7.*-2.0,r1.*r2.*t6.*t7.*-2.0,t6.*(ro1.*t2.*2.0+ro2.*t2.*2.0+ro3.*t2.*2.0-t2.*t5.*6.0-t3.*t5.*6.0)],[2,2]);
