function tensor_K_ro = g_tensor_K_ro(in1,in2)
%G_TENSOR_K_RO
%    TENSOR_K_RO = G_TENSOR_K_RO(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Dec-2019 15:42:32

r1 = in1(1,:);
r2 = in1(2,:);
t2 = r2.^2;
t3 = r1.^2;
t4 = t2+t3;
t5 = 1.0./t4.^(3.0./2.0);
t6 = t2.*t5.*2.0;
t7 = t3.*t5.*2.0;
tensor_K_ro = reshape([t6,r1.*r2.*t5.*-2.0,r1.*r2.*t5.*-2.0,t7,t6,r1.*r2.*t5.*-2.0,r1.*r2.*t5.*-2.0,t7,t6,r1.*r2.*t5.*-2.0,r1.*r2.*t5.*-2.0,t7],[4,3]);
