function tensor_K_r = g_tensor_K_r(in1,in2)
%G_TENSOR_K_R
%    TENSOR_K_R = G_TENSOR_K_R(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Dec-2019 15:42:32

r1 = in1(1,:);
r2 = in1(2,:);
ro1 = in2(1,:);
ro2 = in2(2,:);
ro3 = in2(3,:);
t2 = r2.^2;
t3 = r1.^2;
t4 = t2+t3;
t5 = 1.0./t4.^(5.0./2.0);
t6 = ro1+ro2+ro3;
t8 = t3.*2.0;
t7 = t2-t8;
t9 = t2.*2.0;
t10 = t3-t9;
tensor_K_r = reshape([r1.*t2.*t5.*t6.*-6.0,r2.*t5.*t6.*t7.*-2.0,r2.*t5.*t6.*t7.*-2.0,r1.*t5.*t6.*t10.*-2.0,r2.*t5.*t6.*t7.*-2.0,r1.*t5.*t6.*t10.*-2.0,r1.*t5.*t6.*t10.*-2.0,r2.*t3.*t5.*t6.*-6.0],[4,2]);
