function vS_0 = g_vS_0(in1,in2)
%G_VS_0
%    VS_0 = G_VS_0(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Dec-2019 15:42:32

r1 = in1(1,:);
r2 = in1(2,:);
ro1 = in2(1,:);
ro2 = in2(2,:);
ro3 = in2(3,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = t2+t3;
t5 = 1.0./t4.^(3.0./2.0);
t6 = ro1+ro2+ro3;
t7 = t4.^(3.0./2.0);
vS_0 = [t5.*(t7.*-3.0+ro1.*t3+ro2.*t3+ro3.*t3).*2.0;r1.*r2.*t5.*t6.*-2.0;r1.*r2.*t5.*t6.*-2.0;t5.*(t7.*-3.0+ro1.*t2+ro2.*t2+ro3.*t2).*2.0];
